export const  data =[
    {
        id:1,
        Brand:"Wix",
        icon:"/wix.png",
        description:"No code website builder that comes equipped with business tools that can help you build something as simple as a personal ",
         user:"/user2.jpg",
         categories:["Automation"],
         categoryColor:"purple-700",
         tags:["#DigitalTransformation"],
         Meeting:"in 30 minutes",
    },
    {
        id:2,
        Brand:"Shopify",
        icon:"/shopify.png",
        description:"Complete commerce platform that lets  start, manage, and grow a business.",
         user:"/user2.jpg",
         categories:["E-commerce","B2B"],
         categoryColor:"green-700",
         tags:["#OnlineShopping"],
         Meeting:"Tomorrow",
    },
    {
        id:3,
        Brand:"MailChimp",
        icon:"/mail.png",
        description:"Use real-time behavior data and AI to convert more customers with Mailchimp's marketing, automation & email marketing platform.",
         user:"/user3.jpg",
         categories:["SAAS","Mobile"],
         categoryColor:"red-500",
         tags:["#TechInnovation"],
         Meeting:"Tomorrow",
    },
    {
        id:4,
        Brand:"PayPal",
        icon:"/paypal.png",
        description:"Online payment system that allows you to send and receive money around the world.",
         user:"/user4.jpeg",
         categories:["Marketplace"],
         categoryColor:"green-400",
         tags:["#BuySellOnline"],
         Meeting:"in 6 hours",
    },
    {
        id:5,
        Brand:"Disney",
        icon:"/disney.png",
        description:"American multinational mass media and enternatinment conglomerate that is headquartered at the Walt ",
         user:"/user5.jpg",
         categories:["B2B","B2C"],
         categoryColor:"yellow-200",
         tags:["BusinessPartnerships"],
         Meeting:"No contact",
    },
    {
        id:6,
        Brand:"Intercom",
        icon:"/intercom.png",
        description:"Powerful, easy-to-use platform. Get all your automation, conversations, tickets, customer data, and reporting working together seamlessly",
         user:"/user1.jpg",
         categories:["Technology","SAAS"],
         categoryColor:"green-300",
         tags:["#SmartFinance"],
         Meeting:"in 1 hour",
    },
    {
        id:7,
        Brand:"Google",
        icon:"/google.png",
        description:"American multinational corporation and technology company focusing on online advertising, search engine",
         user:"/user2.jpg",
         categories:["Finance","Automation"],
         categoryColor:"purple-200",
         tags:["#SmartFinance","Workflow"],
         Meeting:"in 30 minutes",
    },
    {
        id:8,
        Brand:"Evernote",
        icon:"/evernote.png",
        description:" Harness the power of the internet with Web Clipper. Scan and store your important files, documents, and images",
         user:"/user3.jpg",
         categories:["Transportation"],
         categoryColor:"yellow-300",
         tags:["LogisticsTech","#UX"],
         Meeting:"Next month",
    },
    {
        id:9,
        Brand:"Microsoft",
        icon:"/microsoft.png",
        description:"Microsoft is a leading global vendor of computer software; hardware for computer, mobile and gaming systems; and cloud services.",
         user:"/user5.jpg",
         categories:["Publishing","B2C"],
         categoryColor:"red-400",
         tags:["B2CMarketing","RetailIT"],
         Meeting:"No contact",
    },
    {
        id:10,
        Brand:"Invision",
        icon:"/invision.png",
        description:"online whiteboard and productivity platform powering the future of work. See how InVision Freehand is purpose-built for team collaboration",
         user:"/user4.jpeg",
         categories:["Web Services"],
         categoryColor:"blue-500",
         tags:["APIIntegration"],
         Meeting:"Next month",
    },
]